language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt

script: 
  - export PYTHONPATH=llevame
  - pytest llevame/ --cov=llevame

after_success:
  - codecov

deploy:
  provider: heroku
  api_key:
    secure: "fdf87151-fe53-49a7-8f2d-c88c4c788ad6"
    app: llevame-taller2
  run:
    - heroku container:push web --app llevame-taller2
